name: Build & Push Image

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service Name'
        required: true


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SERVICE_NAME: ${{ github.event.inputs.service_name }}
  BUILD_NUMBER: ${{ github.run_number }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set lowercase owner
        id: organization
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}

      - name: Build and push docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.organization.outputs.lowercase }}/${{ env.SERVICE_NAME }}:${{ env.BUILD_NUMBER }}

